[package]
name = "superh"
version = "0.2.1"
authors = ["christianttt"]
edition = "2024"
description = "Disassembler for the SuperH (SH) instruction set (SH1/2/3/4)"
license = "MIT"
readme = "README.md"
repository = "https://github.com/christianttt/superh"
categories = ["no-std", "parser-implementations"]
keywords = ["disassembler", "superh", "sh4", "sega", "dreamcast"]

[lints]
workspace = true

[features]
default = ["sh1", "sh2", "sh3", "sh4"]
sh1 = []
sh2 = ["sh1"]
sh3 = ["sh2"]
sh4 = ["sh3"]

[dependencies]
